# Generated by Django 5.1.7 on 2025-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_request_action_request_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
    ]
