# Generated by Django 5.1.7 on 2025-03-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_category_event_cat_one_location_event_loc_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='event_cat_one',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_one_time',
        ),
        migrations.RemoveField(
            model_name='location',
            name='event_loc_one',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_one_time',
        ),
    ]
