# Generated by Django 5.1.7 on 2025-04-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_category_event_cat_one_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
